set shiftwidth=2
set tabstop=2
set softtabstop=2
set expandtab
set cindent

augroup filetype_settings
  autocmd!
  autocmd FileType make setlocal noexpandtab tabstop=4 shiftwidth=4
augroup END

" check env & set clipboard
if $GLFW_IM_MODULE != ""
  set clipboard=unnamedplus
endif

set number
set relativenumber
set cursorline

" auto go to leave
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

source $VIMRUNTIME/defaults.vim
set hlsearch

set mouse=a

call plug#begin()

Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'mattn/vim-lsp-settings'
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() : "\<cr>"

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
let g:airline_theme='onedark'
let g:airline_left_sep=''
let g:airline_left_alt_sep=''
let g:airline_right_sep=''
let g:airline_right_alt_sep=''

Plug 'FittenTech/fittencode.vim'

call plug#end()

syntax on
colorscheme evening
hi Normal ctermbg=NONE
hi EndOfBuffer ctermbg=NONE
